apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
  namespace: staging
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: ghost
      sourceRef:
        kind: HelmRepository
        name: ghost-repo
        namespace: flux-system
      version: "21.1.20"
  values:
    replicaCount: 1
    mariadb:
      enabled: false
    mysql:
      enabled: false
    image:
      registry: docker.io
      repository: bitnami/ghost
      tag: 6.0.5-debian-12-r0
    externalDatabase:
      host: "placeholder"
      user: "placeholder"
      existingSecret: db-secret
      existingSecretPasswordKey: password
    service:
      type: ClusterIP
      port: 80
      targetPort: 2368
    ingress:
      enabled: true
      hostname: app.staging.local
  valuesFrom:
    - kind: ConfigMap
      name: ghost-db-config
      valuesKey: DB_HOST
      targetPath: externalDatabase.host
    - kind: ConfigMap
      name: ghost-db-config
      valuesKey: DB_USER
      targetPath: externalDatabase.user
    - kind: ConfigMap
      name: ghost-db-config
      valuesKey: DB_NAME
      targetPath: externalDatabase.database
    - kind: ConfigMap
      name: ghost-db-config
      valuesKey: DB_PORT
      targetPath: externalDatabase.port
    - kind: Secret
      name: db-secret
      valuesKey: password # The key inside your secret
      targetPath: ghostPassword
