apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
spec:
  chart:
    spec:
      chart: ghost
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 19.0.0
  values:
    replicaCount: 1
    image:
      registry: docker.io
      repository: bitnami/ghost
      tag: 6-alpine
    externalDatabase:
      host: $(DB_HOST)
      user: $(DB_USER)
      password:
        valueFrom:
          secretKeyRef:
            name: ghost-db-secret
            key: password
      database: $(DB_NAME)
      port: $(DB_PORT)
    ingress:
      enabled: true
      hostname: app.staging.local
