apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: postgres-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./infrastructure/cnpg"
  prune: true
  timeout: 1m
